const AСTypes = {
  AUTH: "AUTH",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  USER_ROLE: "USER_ROLE",
  SHOW_USERS_LIST: "SHOW_USERS_LIST",

  ALL_ENTRIES: "ALL_ENTRIES",
  ADD_ENTRY: "ADD_ENTRY",
  EDIT_ENTRY: "EDIT_ENTRY",
  DELETE_ENTRY: "DELETE_ENTRY",
  LIKE_ENTRY: "LIKE_ENTRY",
  CURRENT_IMG: "CURRENT_IMG",
  EDIT_ENTRY_INFO: "EDIT_ENTRY_INFO",
  CHANGE_USER_AVATAR_IN_BLOG: "CHANGE_USER_AVATAR_IN_BLOG",

  MAP: "MAP",
  POINT: "POINT", // позиция по клику
  CURRENT_IMG_MAP: "CURRENT_IMG_MAP",
  CONFIRM_POINT: "CONFIRM_POINT",
  DELETE_POINT: "DELETE_POINT",
  WECLOME_COMPONENT: "WECLOME_COMPONENT",
  ADD_STAR_POINT: "ADD_STAR_POINT",

  CURRENT_IMG_USER: "CURRENT_IMG_USER",
  CURRENT_IMG_CLEAR: "CURRENT_IMG_CLEAR",
  GET_IMG: "GET_IMG",
  SET_IMG: "SET_IMG",
  GET_RATING: "GET_RATING",
  SET_RATING: "SET_RATING",

  ALL_COMMENTS: "ALL_COMMENTS",
  ADD_COMMENT: "ADD_COMMENT",
  LOADING_COMMENTS: "LOADING_COMMENTS",
  DELETE_COMMENT: "DELETE_COMMENT",
};

export default AСTypes;
